---
- name: Install java 8
  include_role:
    name: java8_setup

- name: Add apt-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    update_cache: yes
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

- name: Run apt-get update
  apt:
    update_cache: yes
  changed_when: False

- name: Install required packages
  apt:
    name: elasticsearch
    state: present
    allow_unauthenticated: yes

- name: start elastic search service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Expose elastic search for remote access
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'network.host: 0.0.0.0'
    state: present

- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
